### ISSUE TITLE
Migration of `auth_tokens` table fails

### ISSUE THREAD

**Issue by neeooh** [m-thalmann/Cookbook#6]
Hello Matthias!

First of all, thank you for creating this app, I re-used it for one of my project ideas :)

Could you upload latest/complete laravel migration files please? (specifically to create the auth_tokens table)

There is a migration file to add **some** fields to the auth_token table:
2023_08_23_180717_add_request_fields_to_auth_tokens_table.php
But there is no migration to create the table itself, and the rest of the fields that should be in the auth_table.

**More details:**
When run `php artisan migrate` it threw errors. I have noticed there is no migration to create the _auth_tokens_ table.

At first, I created my own migration file to create the auth_tokens table, and it worked on my localhost with a demo mode (the demo account already created by seeding). However, in an empty/clean environment (no seeded data in database), when I create a new user, it throws errors about missing columns (I didn't have those columns in the migration file I created). After adding those missing columns (according to the AuthTokenSchema.php) manually in PhpMyAdmin, I was able to register a new user, however, after the re-direct to the home page, I get the Error 401 Unauthorised under categories and recipes.
Looking at the Network requests, the client uses a token which doesn't exist in the database, then calls the /refresh api endpoint, which also returns a token which doesn't exists in the auth_tokens table.

I think all of those problems exists because I have an incorrect auth_tokens schema. 

Thanks in advance! :)

**Comment by m-thalmann** [comment]
Hi @neeooh,
no problem :)

The migration files are up to date... The auth tokens table is created through the used library: https://github.com/m-thalmann/laravel-token-auth
So the only reason I could think of why this is not working for you, is that you have removed that package from the `composer.json`.

Hope this helps :)

**Comment by neeooh** [comment]
Wow, I wasn't expecting a reply on Sunday! Thank you! I tested everything on that day and your feedback was actually very helpful!

For clarification sake, 
I did not remove your package m-thalmann/laravel-token-auth. It was correctly installed. When I run the migrate script, I get error:

```
2023_07_19_000000_create_auth_tokens_table ............................................................................................ 6ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'abilities' can't have a default value (Connection: mysql, SQL: create table `auth_tokens` (`id` bigint unsigned not null auto_increment primary key, `type` varchar(255) not null, `authenticatable_type` varchar(255) not null, `authenticatable_id` bigint unsigned not null, `group_id` int null, `name` varchar(255) null, `token` varchar(64) not null, `abilities` text not null default '[]', `revoked_at` timestamp null, `expires_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

To fix that problem, in file:
`api/vendor/m-thalmann/laravel-token-auth/database/migrations/2023_07_19_000000_create_auth_tokens_table.php`
line 16, changed from:
`$table->text('abilities')->default('[]');`
to
`$table->string('abilities')->default('[]');`

That resolved the issue completely. Now I can sign-up and the redirect is working properly.

I am happy to make a pull request to your package, if you want?

Thanks again for help 👍 💯

**Comment by m-thalmann** [comment]
No worries ;)

Hmm I see the problem, this happened to me too now. All tests (and also my local dev setup) are running using SQLite, where it does not seem to be an issue...

This is definitely a fix, but I would like to keep using `text`. I will find a solution and add tests for MySQL to prevent such problems in future.

I'll keep this issue updated 👍

**Comment by m-thalmann** [comment]
@neeooh This should be fixed now. Can you confirm? If you still have problems feel free to reopen/create a new issue :)
